### ISSUE TITLE
Ping here if you want to contribute or receive notification about meetings

### ISSUE THREAD

**Issue by fserb** [WICG/canvas-place-element#4]

**Comment by ydaniv** [comment]
Thanks! ✋

**Comment by collin** [comment]
I have an interest in hearing about meetings/discussing particular use-cases if that would be useful. I have an interest in these apis for placing text/css styled elements in canvases for:

- wysiwyg graphic/motion design applications
- drawing canvas/dom nodes to video frames for webcodecs

**Comment by fserb** [comment]
Next meeting here: https://github.com/WICG/canvas-place-element/issues/17
